#hello_the_world = le nom de la route /
#path=url / defaults = paramètres de la route

#le nom de la route
nh_platform_home:
#une entrée (ligne path) : URL à capturer
                        #on rajoute le param page pour avoir une url plus propre
    path:    /{page}
#    une sortie (ligne defaults) : paramètres de la route qui dit quel contrôleur appeler
    defaults:
        _controller: NHPlatformBundle:Advert:index
        page:    1
    requirements:
        page: \d*

#le routeur est donc à partir d'une URL, de trouver la route correspondante et de retourner les param de sortie
nh_platform_view:
    path:    /advert/view/{id}
    defaults:
        _controller: NHPlatformBundle:Advert:view

#nh_platform_affichage:
#    path:    /advert/{id}
#    defaults:
#        _controller: NHPlatformBundle:Advert:affichage
#    requirements:
#        id: \d+

nh_platform_add:
    path:    /add
    defaults:
        _controller: NHPlatformBundle:Advert:add

nh_platform_edit:
    path:    /edit/{id}
    defaults:
        _controller: NHPlatformBundle:Advert:edit
    requirements:
        id: \d+

nh_platform_delete:
    path:    /delete/{id}
    defaults:
        _controller: NHPlatformBundle:Advert:delete
    requirements:
        id: \d+


#nh_platform_affichage_params:
#    path:    /{year}/{params}.{format}
#    #le tableau defaults correspond aux valeurs par défaut de nos params
#    defaults:
#        _controller: NHPlatformBundle:Advert:affichageParams
#        format:    html
##        on déclare là les requirements pour déterminer les contraintes que doivent respecter les params
#    requirements:
##    d{4} = 4 chiffres à la suite
#        year:    \d{4}
#        #pareil pour html/xml, le .rss ne sera pas interceptée
#        format: html|xml

nh_platform_page2:
    path:     /page2
    defaults:
        _controller: NHPlatformBundle:Advert:secondepage

#chaque route fait la correspondance entre une URL et un jeu de paramètres
#le paramètre qui nous intéresse est _controlle/avertr = le contrôleur à exécuter