# src/NH/PlatformBundle/Resources/config/services.yml

#services:
#    nh_platform.example:
#        class: NH\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

services:
    nh_platform.email.application_mailer:
      class: NH\PlatformBundle\Email\ApplicationMailer
      arguments:
          - "@mailer"

#services:
#    nh_platform.doctrine_listener.application_creation:
#        class: NH\PlatformBundle\DoctrineListener\ApplicationCreationListener
#        arguments:
#            - "@nh_platform.email.application_mailer"
#        tags:
#            - { name: doctrine.event_listener, event: postPersist }