<?php

namespace NH\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    //cette fonction va retourner un tableau Advert
    public function getAdvertWithCategories(array $categoryNames)
    {
        $qb = $this->createQueryBuilder('a');
        //jointure entre l'entité category avec pour alias "c"
        $qb
            ->innerJoin('a.categories', 'c')
            ->addSelect('c')
            ;
        //on filtre sur le nom des catégories à l'aide d'un IN
        $qb->where($qb->expr()->in('c.name', $categoryNames));

        // on retourne le résultat
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    /*public function myFindAll()
    {
        // Méthode 2 :
        $queryBuilder = $this->createQueryBuilder('a');

        // On n'ajoute pas de critère ou tri particulier, la construction
        // de notre requête est finie
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        // On retourne ces résultats
        return $results;
    }
    public function myFindOne($id)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.id = :id')
            ->setParameter('id', $id)
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }*/
}